language: node_js
node_js:
  - '10'
branches:
  only:
    - master
before_script:
  - npm install
script:
  - npm run test:coverage
  - npm run coveralls

after_success:
  - npm run build

deploy:
  provider: npm
  api_token: $NPM_API_KEY
  skip_cleanup: true
